### ISSUE TITLE
opencascde.js not working in node.js

### ISSUE THREAD

**Issue by demike** [donalffons/opencascade.js#80]
when using opencascade.js@beta the following error occures.
This seams to be related to node.js es module resolution 

```
import ocFullJS from "./opencascade.full.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\c2k\CC4.0_DEV\CC4.0\tools\3dworkflow\src\index.js:1:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

The index.js file looks like

```
let oc = require('opencascade.js');
```
or 
```
import initOpenCascade from 'opencascade.js';
```
when I use 
``` 
"type": "module" 
```
in the package.json

**Comment by donalffons** [comment]
I made the changes I mentioned earlier and added some lines of documentation to the main README.md.

Startup time on my system is around 2:00 - 2:30 min until the library is usable in NodeJS v12/v15. Again, those times would  be significantly shorter for a custom build version of the library. However, this approach would require you to re-build the library each time you're using a new class (which should take anywhere between seconds up to a few minutes, depending on the number of symbols you're using).

I would really hope for NodeJS to implement some sort of caching strategy for WASM soon.

**Comment by donalffons** [comment]
Small update regarding the startup times: NodeJS (I'm using v15) can actually start executing code before the compilation stage (I assume it's also optimizing) has completed. I just added some tests back in to the build system and those tests complete after 20s. Still not great, but certainly better than > 2:00 min.
